# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bqdf',
                'doc_host': 'https://motdam.github.io',
                'git_url': 'https://github.com/motdam/bqdf',
                'lib_path': 'bqdf'},
  'syms': { 'bqdf.core': { 'bqdf.core.Table': ('core.html#table', 'bqdf/core.py'),
                           'bqdf.core.Table.id': ('core.html#table.id', 'bqdf/core.py'),
                           'bqdf.core.build': ('core.html#build', 'bqdf/core.py'),
                           'bqdf.core.convert_bq_dtypes': ('core.html#convert_bq_dtypes', 'bqdf/core.py'),
                           'bqdf.core.ex': ('core.html#ex', 'bqdf/core.py'),
                           'bqdf.core.exists': ('core.html#exists', 'bqdf/core.py'),
                           'bqdf.core.get_size_gb': ('core.html#get_size_gb', 'bqdf/core.py'),
                           'bqdf.core.read': ('core.html#read', 'bqdf/core.py'),
                           'bqdf.core.to': ('core.html#to', 'bqdf/core.py')}}}
