# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bqdf',
                'doc_host': 'https://motdam.github.io',
                'git_url': 'https://github.com/motdam/bqdf',
                'lib_path': 'bqdf'},
  'syms': {'bqdf.core': {'bqdf.core.foo': ('core.html#foo', 'bqdf/core.py')}}}
