"""Ergonomic wrapper for pandas_gbq that simplifies loading BigQuery data into DataFrames"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read', 'convert_bq_dtypes', 'to', 'ex', 'Table', 'exists', 'ensure']

# %% ../nbs/00_core.ipynb 5
from pandas_gbq import read_gbq as _original_read_gbq, to_gbq as _original_to_gbq, Context, context
import pandas as pd, re, time
from decimal import Decimal
from google.cloud import bigquery
from dataclasses import dataclass
from google.cloud import bigquery
from google.cloud.exceptions import NotFound
from google.oauth2 import service_account
from google.auth import default
import os
import json

# %% ../nbs/00_core.ipynb 7
def _get_credentials():
    creds_json = os.getenv('GOOGLE_CREDENTIALS_JSON')
    if creds_json: return service_account.Credentials.from_service_account_info(json.loads(creds_json))
    creds, _ = default()
    return creds

# %% ../nbs/00_core.ipynb 9
def read(
    query_or_table:str, # SQL query string or table reference
    verbose:bool=True, # Print timing and DataFrame info
    convert_dtypes:bool=True, # Apply type conversion to columns
    date_cols:list=None, # List of columns to convert to datetime
    str_cols:list=["scv_id"], # List of columns to keep as string/object type
    use_bqstorage_api:bool=True, # Use BigQuery Storage API for faster reads
    credentials=None, # Optional explicit credentials
    **kwargs
    ):
    start = time.time()
    creds = credentials or _get_credentials()
    df = _original_read_gbq(query_or_table, use_bqstorage_api=use_bqstorage_api, credentials=creds, **kwargs)
    if convert_dtypes: df = convert_bq_dtypes(df, date_cols=date_cols, str_cols=str_cols)
    read_type = 'table' if re.match(r"""^[`\w\-]+\.[\w\-]+.[\w\-\`]+$""", query_or_table) else 'query'
    if verbose:
        elapsed = time.time() - start
        size_gb = _get_size_gb(df)
        print(f"Loaded {len(df)} rows × {len(df.columns)} cols ({size_gb:.4f} GB) from {read_type} in {elapsed:.2f}s")
        print(df.info())
    return df

# %% ../nbs/00_core.ipynb 11
def convert_bq_dtypes(
    df:pd.DataFrame, # DataFrame to convert
    date_cols:list=None, # List of columns to convert to datetime
    str_cols:list=None # List of columns to keep as string/object type
):
    "Convert BigQuery data types to pandas-compatible types"
    df = df.copy()
    date_cols = set(date_cols or [])
    str_cols = set(str_cols or [])
    for col in df.columns:
        if col in str_cols: df[col] = df[col].astype('object')
        elif re.search(r"(date|timestamp)", col.lower()) or col in date_cols: df[col] = pd.to_datetime(df[col], errors='coerce')
        elif df[col].dtype == 'float64': df[col] = df[col].astype('Float64')
        elif df[col].dtype == 'int64': df[col] = df[col].astype('Int64')
        elif df[col].dtype == 'object':
            first_val = df[col].dropna().iloc[0] if len(df[col].dropna()) > 0 else None
            if first_val is not None and isinstance(first_val, Decimal): df[col] = df[col].astype('Float64')
    return df

# %% ../nbs/00_core.ipynb 13
def to(
    df:pd.DataFrame, # DataFrame to write to BigQuery
    destination_table:str, # Destination table in format 'project.dataset.table' or 'dataset.table'
    verbose:bool=True, # Print timing and data size info
    credentials=None, # Optional explicit credentials
    **kwargs
):
    "Write DataFrame to BigQuery table"
    start = time.time()
    creds = credentials or _get_credentials()
    result = _original_to_gbq(df, destination_table, credentials=creds, **kwargs)
    if verbose:
        elapsed = time.time() - start
        size_gb = _get_size_gb(df)
        print(f"Sent {len(df)} rows × {len(df.columns)} cols ({size_gb:.4f} GB) to {destination_table} in {elapsed:.2f}s")
    return result

# %% ../nbs/00_core.ipynb 15
def _get_size_gb(df):
    return df.memory_usage(deep=True).sum() / 1024**3


# %% ../nbs/00_core.ipynb 17
def ex(query:str, project_id:str=None, verbose:bool=True, credentials=None, **kwargs):
    "Execute query in BigQuery without returning results"
    project_id = project_id or os.getenv('GCP_PROJECT')
    if not project_id: raise ValueError("Set GCP_PROJECT env var or pass project_id")
    creds = credentials or _get_credentials()
    client = bigquery.Client(project=project_id, credentials=creds, **kwargs)
    start = time.time()
    job = client.query(query)
    result = job.result()
    if verbose:
        elapsed = time.time() - start
        gb_processed = (job.total_bytes_processed or 0) / 1024**3
        rows_affected = job.num_dml_affected_rows if job.num_dml_affected_rows else 0
        cached = " (cached)" if job.cache_hit else ""
        print(f"Processed {gb_processed:.4f} GB{cached}, {rows_affected} rows affected in {elapsed:.2f}s")
    return result

# %% ../nbs/00_core.ipynb 19
@dataclass
class Table:
    project: str
    dataset: str
    name: str
    
    @classmethod
    def from_id(cls, table_id:str):
        parts = table_id.replace('`','').split('.')
        if len(parts) == 3: return cls(*parts)
        if len(parts) == 2: return cls(os.getenv('GCP_PROJECT'), *parts)
        raise ValueError(f"Invalid table_id: {table_id}")
    
    @property
    def id(self): return f"{self.project}.{self.dataset}.{self.name}"

    def __str__(self): return self.id



# %% ../nbs/00_core.ipynb 21
def exists(table_id:str, project_id:str=None, credentials=None, verbose:bool=False, **kwargs):
    "Check if a BigQuery table exists"
    project_id = project_id or os.getenv('GCP_PROJECT')
    if not project_id: raise ValueError("Set GCP_PROJECT env var or pass project_id")
    if isinstance(table_id, Table): table_id = table_id.id
    elif table_id.count('.') == 1: table_id = f"{project_id}.{table_id}"
    creds = credentials or _get_credentials()
    client = bigquery.Client(credentials=creds, project=project_id, **kwargs)
    try:
        client.get_table(table_id)
        if verbose: print(f"Table {table_id} exists")
        return True
    except NotFound:
        if verbose: print(f"Table {table_id} not found")
        return False

# %% ../nbs/00_core.ipynb 23
def ensure(table_id:str, query:str, project_id:str=None, force:bool=False, verbose:bool=True, credentials=None, **kwargs):
    "Read table if exists, otherwise create from query then read"
    project_id = project_id or os.getenv('GCP_PROJECT')
    if not project_id: raise ValueError("Set GCP_PROJECT env var or pass project_id")
    creds = credentials or _get_credentials()
    if not exists(table_id, project_id=project_id, credentials=creds, verbose=verbose) or force:
        create_query = f"CREATE OR REPLACE TABLE {table_id} AS {query}"
        ex(create_query, project_id=project_id, credentials=creds, verbose=verbose)
    return read(table_id, verbose=verbose, credentials=creds, **kwargs)
