"""Ergonomic wrapper for pandas_gbq that simplifies loading BigQuery data into DataFrames"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read', 'to', 'ex', 'convert_bq_dtypes']

# %% ../nbs/00_core.ipynb 6
from pandas_gbq import read_gbq as _original_read_gbq, to_gbq as _original_to_gbq, Context, context
import pandas as pd, re, time
from decimal import Decimal
from google.cloud import bigquery


# %% ../nbs/00_core.ipynb 9
def read(
    query_or_table:str, # SQL query string or table reference
    verbose:bool=True, # Print timing and DataFrame info
    convert_dtypes:bool=True, # Apply type conversion to columns
    date_cols:list=None, # List of columns to convert to datetime
    str_cols:list=["scv_id"], # List of columns to keep as string/object type
    use_bqstorage_api:bool=True, # Use BigQuery Storage API for faster reads
    **kwargs
    ):
    start = time.time()
    df = _original_read_gbq(query_or_table, use_bqstorage_api=use_bqstorage_api, **kwargs)
    if convert_dtypes: df = convert_bq_dtypes(df, date_cols=date_cols, str_cols=str_cols)
    if verbose:
        elapsed = time.time() - start
        print(f"Retrieved {len(df)} rows × {len(df.columns)} cols in {elapsed:.2f}s")
        print(df.info())
    return df

def to(dataframe, destination_table, **kwargs):
    "Write DataFrame to BigQuery table"
    return _original_to_gbq(dataframe, destination_table, **kwargs)

def ex(query, project_id='petsathome-sb-datascience', **kwargs):
    "Execute query in BigQuery without returning results (useful for DDL)"
    client = bigquery.Client(project=project_id)
    job = client.query(query, **kwargs)
    return job.result()

def convert_bq_dtypes(df, date_cols=None, str_cols=None):
    "Convert BigQuery data types to pandas-compatible types"
    df = df.copy()
    date_cols = set(date_cols or [])
    str_cols = set(str_cols or [])
    for col in df.columns:
        if col in str_cols: df[col] = df[col].astype('object')
        elif re.search(r"(date|timestamp)", col.lower()) or col in date_cols: df[col] = pd.to_datetime(df[col], errors='coerce')
        elif df[col].dtype == 'float64': df[col] = df[col].astype('Float64')
        elif df[col].dtype == 'int64': df[col] = df[col].astype('Int64')
        elif df[col].dtype == 'object':
            first_val = df[col].dropna().iloc[0] if len(df[col].dropna()) > 0 else None
            if first_val is not None and isinstance(first_val, Decimal): df[col] = df[col].astype('Float64')
    return df


